language: objective-c

before_script:
    - brew update

script:
   - xcodebuild clean build -sdk iphonesimulator -workspace MovieInvolved.xcworkspace -scheme MovieInvolved CODE_SIGNING_REQUIRED=NO

branches:
  only:
    - master
