language: objective-c

before_script:
    - brew update

script:
    - xctool -workspace MovieInvolved.xcworkspace -scheme MovieInvolved -sdk iphonesimulator build test

branches:
  only:
    - master
